export const GLOSSARY = [
  {term: "poverty headcount ratio", definition: "The poverty headcount ratio measures the share of the population for which total consumption expenditure falls below a defined poverty line, expressed here in $3.10 or $1.90/per-capita/day in 2011 international purchasing power parity (see below), identifying general and extreme poverty, respectively."},
  {term: "poverty gap ratio", definition: "The poverty gap index measures the depth of poverty (how far consumption expenditures of the poor are from the poverty line), providing an index of shortfall from the poverty line. The poverty headcount ratio ignores the depth of poverty since poor population eventually becoming even poorer would leave the headcount ratio unchanged, contrary to the poverty gap index that would increase."},
  {term: "poverty severity ratio", definition: "The poverty severity index aims at giving more weights to the extreme poor, taking into account the inequality among the poor by squaring the poverty gap ratio."},
  {term: "Purchasing power parity", definition: "The PPP factor is measured by adjusted exchange rate for each country that equalizes the nominal exchange rate in terms of the local cost of a common basket of goods and services. For this platform, monetary values in all countries in different years have been converted to international dollars at the 2011 PPP conversion rate."},
  {term: "rainfall variability", definition: "A measure of how much rainfall varies from the long-term average, expressed here as the percentage of crop land area experienced the coefficient of variation of annual rainfall greater than 20% between 1990 and 2015."},
  {term: "Stunting Rate", definition: "The proportion of stunting is expressed as the percentage of children with a low height for age z-score (below minus two standard deviations from median height for age of the given standard population), reflecting a sustained past episode or episodes of chronic undernutrition, which is impacted by maternal and child food, heath and care before and during pregnancy and during the first two years of life."},
  {term: "Underweight Rate", definition: "The proportion of underweight is expressed as the percentage of children with low weight for age z-score (below minus two standard deviations from median weight for age of the given standard population), reflecting a current condition resulting from inadequate food intake, past episodes of undernutrition and/or poor health conditions, combination of both chronic and acute undernutrition."},
  {term: "Wasting Rate", definition: "The proportion of wasting is expressed as the percentage of children with a low weight for height z-score (below minus two standard deviations from median weight for height of the given standard population), generally reflecting acute weight loss associated with a recent period of hunger and/or disease."}
];

GLOSSARY.findTerm = function(term) {
  const obj = this.filter(obj => obj.term === term);
  return obj ? obj[0].definition : null;
};
